### PR TITLE
I did some meth

### PR DESCRIPTION
**Pull request by MrNegetZ**
I added PDFs and a page for the 2 third party stuff we use and also the virtues for sword cause why not.

### CODE REVIEW

**Comment by MrNegetZ** [comment]
The <resource src="linktopdf"/> was so it would also show up on writerside!!

**Comment by MrNegetZ** [comment]
L removing of the PDF. How are they going to know all the imbuements??!!

**Review by LewisIsWorking — APPROVED** [review]
Thanks

**Comment by LewisIsWorking** [comment]
> L removing of the PDF. How are they going to know all the imbuements??!!

It's copyrighted information.

All the rules are available at the link provided to Easy Tools.

**Comment by LewisIsWorking** [comment]
> L removing of the PDF. How are they going to know all the imbuements??!!

It's copyrighted information.

All the rules are available at the link provided to Easy Tools.

**Pull request merged**
